php-tuf/composer-stager

.idea/composer-stager.iml
composer.json
composer.lock
config/services.yml
src/Infrastructure/Process/FileCopier/SymfonyFileCopier.php
tests/Functional/AbstractFileCopierTest.php
tests/Functional/RsyncFileCopierTest.php
tests/Functional/SymfonyFileCopierTest.php
tests/Unit/Infrastructure/Process/FileCopier/SymfonyFileCopierTest.php

...and fix directory recursion. 😬

Add support to Symfony file copier for exclusions

---

composer.lock

| Production Changes           | From   | To      | Compare                                                                         |
|------------------------------|--------|---------|---------------------------------------------------------------------------------|
| psr/container                | 1.1.1  | 1.1.2   | [...](https://github.com/php-fig/container/compare/1.1.1...1.1.2)               |
| symfony/config               | v5.3.4 | v5.3.10 | [...](https://github.com/symfony/config/compare/v5.3.4...v5.3.10)               |
| symfony/console              | v5.3.7 | v5.3.10 | [...](https://github.com/symfony/console/compare/v5.3.7...v5.3.10)              |
| symfony/dependency-injection | v5.3.7 | v5.3.10 | [...](https://github.com/symfony/dependency-injection/compare/v5.3.7...v5.3.10 …

Update Composer libraries

---

composer.lock

| Production Changes | From  | To    | Compare                                                           |
|--------------------|-------|-------|-------------------------------------------------------------------|
| psr/container      | 1.1.2 | 1.1.1 | [...](https://github.com/php-fig/container/compare/1.1.2...1.1.1) |
| Dev Changes               | From    | To      | Compare                                                                      |
|---------------------------|---------|---------|------------------------------------------------------------------------------|
| roave/security-advisories | 7129fb8 | bac54e1 | [...](https://github.com/Roave/SecurityAdvisories/compare/7129fb8...bac54e1) |

Downgrade psr/container library for PHP 7.3 support

---

phpstan.neon.dist
phpstan/Methods/SortedRequiredConstructorParametersRule.php
src/Domain/Core/Committer/Committer.php
src/Infrastructure/Aggregate/PreconditionsTree/CommonPreconditions.php
tests/Domain/Core/Committer/CommitterUnitTest.php
tests/Infrastructure/Aggregate/PreconditionsTree/CommonPreconditionsUnitTest.php

@phenaproxima now that you're autoloading classes, I don't think that reordering constructor parameters in two classes will have any effect on you, but I want to give you a chance to confirm.

Alphabetize all non-optional constructor parameters

---

phpstan.neon.dist
src/Domain/Core/Beginner/Beginner.php
src/Domain/Core/Committer/Committer.php
src/Domain/Service/Precondition/PreconditionInterface.php
src/Infrastructure/Aggregate/PreconditionsTree/AbstractPreconditionsTree.php
src/Infrastructure/Service/Precondition/AbstractPrecondition.php
src/Infrastructure/Service/Precondition/ActiveAndStagingDirsAreDifferent.php
src/Infrastructure/Service/Precondition/ActiveDirExists.php
src/Infrastructure/Service/Precondition/ActiveDirIsWritable.php
src/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinks.php
src/Infrastructure/Service/Precondition/ComposerIsAvailable.php
src/Infrastructure/Service/Precondition/StagingDirDoesNotExist.php
src/Infrastructure/Service/Precondition/StagingDirExists.php
src/Infrastructure/Service/Precondition/StagingDirIsWritable.php
tests/PHPUnit/Domain/Core/Beginner/BeginnerUnitTest.php
tests/PHPUnit/Domain/Core/Cleaner/CleanerUnitTest.php
tests/PHPUnit/Domain/Core/Committer/CommitterUnitTest.php
tests/PHPUnit/Domain/Core/Stager/StagerUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/AbstractPreconditionsTreeUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/BeginnerPreconditionsUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/CleanerPreconditionsUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/CommitterPreconditionsUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/CommonPreconditionsUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/StagerPreconditionsUnitTest.php
tests/PHPUnit/Infrastructure/Aggregate/PreconditionsTree/StagingDirIsReadyUnitTest.php
tests/PHPUnit/Infrastructure/Service/Precondition/AbstractPreconditionUnitTest.php
tests/PHPUnit/Infrastructure/Service/Precondition/PreconditionTestCase.php
tests/PHPUnit/Infrastructure/Service/Precondition/StagingDirExistsUnitTest.php

Note: This doesn't change any preconditions to _do_ anything with the exclusions; it merely to make it possible for them to do so, in preparation for future enhancements.

Add the ability to pass path exclusions to preconditions

---

phpstan.neon.dist
src/Infrastructure/Service/Precondition/ComposerIsAvailable.php
tests/PHPUnit/Infrastructure/Service/Precondition/ComposerIsAvailableFunctionalTest.php
tests/PHPUnit/Infrastructure/Service/Precondition/ComposerIsAvailableUnitTest.php
tests/PHPUnit/Infrastructure/Service/Precondition/PreconditionTestCase.php

Fixes https://www.drupal.org/project/automatic_updates/issues/3321966.

Make Infrastructure\Service\Precondition\ComposerIsAvailable confirm that found Composer executable is actually valid

---

src/Infrastructure/Factory/Path/PathFactory.php
src/Infrastructure/Factory/Path/PathFactoryInterface.php
tests/PHPUnit/Infrastructure/Factory/Path/PathFactoryUnitTest.php

Follow-up to https://github.com/php-tuf/composer-stager/pull/63

Add an optional  argument to Infrastructure\Factory\Path\PathFactoryInterface::create()

---

.idea/dictionaries/project.xml
src/Domain/Service/Filesystem/FilesystemInterface.php
src/Infrastructure/Service/Filesystem/Filesystem.php
tests/PHPUnit/Infrastructure/Service/Filesystem/FilesystemFunctionalTest.php
tests/PHPUnit/Infrastructure/Service/Filesystem/FilesystemUnitTest.php
tests/PHPUnit/TestCase.php

Add the ability to Domain\Service\Filesystem\FilesystemInterface to distinguish between hard links and symlinks

---

README.md
src/Domain/Core/Beginner/BeginnerInterface.php
src/Domain/Core/Committer/CommitterInterface.php
src/Domain/Service/FileSyncer/FileSyncerInterface.php
src/Domain/Value/PathList/PathListInterface.php
src/Infrastructure/Service/FileSyncer/PhpFileSyncer.php
src/Infrastructure/Service/FileSyncer/RsyncFileSyncer.php
src/Infrastructure/Service/Finder/RecursiveFileFinder.php
src/Infrastructure/Service/Finder/RecursiveFileFinderInterface.php
src/Infrastructure/Service/Precondition/AbstractFileIteratingPrecondition.php
src/Infrastructure/Value/PathList/PathList.php
tests/EndToEnd/EndToEndFunctionalTestCase.php
tests/Infrastructure/Service/FileSyncer/RsyncFileSyncerUnitTest.php
tests/Infrastructure/Service/Finder/RecursiveFileFinderFunctionalTest.php
tests/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExistFunctionalTest.php
tests/Infrastructure/Service/Precondition/NoHardLinksExistFunctionalTest.php
tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsFunctionalTest.php
tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseFunctionalTest.php
tests/Infrastructure/Service/Precondition/NoSymlinksPointToADirectoryFunctionalTest.php
tests/Infrastructure/Value/PathList/PathListUnitTest.php
tests/Infrastructure/Value/PathList/TestPathList.php

Resolve #103: Make Infrastructure\Value\PathList\PathList::add() variadic.

---

.idea/php.xml
composer.json
composer.lock

This is a prerequisite of https://github.com/php-tuf/composer-stager/issues/123:
- https://github.com/php-tuf/composer-stager/issues/123.

Add symfony/translation-contracts Composer library

---

phpstan.neon.dist
src/API/Translation/Value/TranslatableInterface.php
src/Internal/Translation/Service/Translator.php
src/Internal/Translation/Value/TranslatableMessage.php
tests/EndToEnd/PhpFileSyncerEndToEndFunctionalTest.php
tests/Exception/ExceptionUnitTest.php
tests/Filesystem/Service/FilesystemFunctionalTest.php
tests/Precondition/Service/NoAbsoluteSymlinksExistFunctionalTest.php
tests/Translation/Service/TranslatorUnitTest.php
tests/Translation/Value/TranslatableMessageUnitTest.php

Closes: https://github.com/php-tuf/composer-stager/issues/179

Add placeholder substitution to TranslatableMessage::__toString()

---

config/services.yml
docs/README.md
docs/services.yml
phpstan.neon.dist
src/Internal/Core/Beginner.php
src/Internal/Core/Committer.php
src/Internal/Precondition/Service/NoSymlinksPointToADirectory.php
tests/Core/BeginnerUnitTest.php
tests/Core/CommitterUnitTest.php
tests/EndToEnd/EndToEndFunctionalTestCase.php
tests/EndToEnd/PhpFileSyncerEndToEndFunctionalTest.php
tests/EndToEnd/RsyncFileSyncerEndToEndFunctionalTest.php
tests/FileSyncer/Factory/PhpFileSyncerFactory.php
tests/FileSyncer/Factory/RsyncFileSyncerFactory.php
tests/Precondition/Service/NoSymlinksPointToADirectoryFunctionalTest.php
tests/Precondition/Service/NoSymlinksPointToADirectoryUnitTest.php
tools/PHPStan/Rules/Files/ExampleServicesConfigIsCurrentRule.php

Inject `FileSyncerFactoryInterface` instead of depending on `FileSyncerInterface` directly

---

src/API/Filesystem/Service/FilesystemInterface.php
src/Internal/Filesystem/Service/Filesystem.php
tests/Filesystem/Service/FilesystemFunctionalTest.php
tests/Filesystem/Service/FilesystemUnitTest.php
tests/TestUtils/AssertTrait.php

See https://github.com/php-tuf/composer-stager/issues/162

Make `API\Filesystem\Service\FilesystemInterface::copy()` preserve file permissions

---

tests/EndToEnd/EndToEndFunctionalTest.php
tests/FileSyncer/Service/FileSyncerFunctionalTest.php

Add tests for syncing permissions and empty directories

---

tests/FileSyncer/Service/FileSyncerFunctionalTest.php
tests/TestUtils/AssertTrait.php

Add tests that the file syncer can copy a Git directory.

---

phpstan.neon.dist
src/Internal/Precondition/Service/CommonPreconditions.php
tests/Precondition/Service/CommonPreconditionsUnitTest.php

Oops. Forgot to actually inject the new preconditions from https://github.com/php-tuf/composer-stager/pull/334 (`RsyncIsAvailable`) and https://github.com/php-tuf/composer-stager/pull/342 (`NoNestingOnWindows`) into `CommonPreconditions`.

Wire new preconditions up to `CommonPreconditions`

---

.github/workflows/main.yml
composer.json
composer.lock
tests/Finder/Service/ExecutableFinderUnitTest.php

Closes https://github.com/php-tuf/composer-stager/issues/350

Make compatible with Symfony 7

---

.github/workflows/main.yml
composer.json
grumphp.yml.dist
infection.json5.dist
phpunit.xml.dist
tests/Compatability/CompatabilityFunctionalTest.php
tests/Compatability/CompatabilityTest.php
tests/Translation/Service/SymfonyTranslatorProxyUnitTest.php
tests/Translation/Service/TranslatorUnitTest.php
tests/Translation/Value/TranslationParametersUnitTest.php

...and isolate compatibility tests into their own job.
- Fixes: https://github.com/php-tuf/composer-stager/issues/349

Update tests to include PHP 8.3 on GitHub Actions

---

docs/SECURITY.md

- Part of #79.
Context/background: https://github.com/php-tuf/composer-stager/issues/79#issuecomment-1452167755

Add SECURITY.md

---

docs/GOVERNANCE.md

- Part of https://github.com/php-tuf/composer-stager/issues/300.

Add GOVERNANCE.md

---

src/API/Core/BeginnerInterface.php
src/API/Core/CleanerInterface.php
src/API/Core/CommitterInterface.php
src/API/Core/StagerInterface.php
src/API/FileSyncer/Service/FileSyncerInterface.php
src/API/Filesystem/Service/FilesystemInterface.php
src/API/Precondition/Service/PreconditionInterface.php
src/API/Process/Service/ComposerProcessRunnerInterface.php
src/API/Process/Service/ProcessInterface.php
src/API/Process/Service/RsyncProcessRunnerInterface.php
src/Internal/Core/Stager.php
src/Internal/FileSyncer/Service/FileSyncer.php
src/Internal/Process/Service/AbstractProcessRunner.php
tests/FileSyncer/Service/FileSyncerFunctionalTest.php
tests/FileSyncer/Service/FileSyncerUnitTest.php

Pass `$timeout` through to `AbstractProcessRunner::run()` in `Internal\FileSyncer\Service\FileSyncer`
