php-tuf/composer-stager

src/Console/Command/CleanCommand.php, src/Domain/Cleaner.php, tests/Console/Command/CleanCommandTest.php, tests/Console/Command/StageCommandTest.php, tests/Domain/CleanerTest.php
Command output:
```
$ ./bin/composer-stage clean --help
Description:
Removes the staging directory
Usage:
clean
Options:
-h, --help                     Display help for the given command. When no command is given display help for the list command
-q, --quiet                    Do not output any message
-V, --version                  Display this application version
--ansi                     Force ANSI output
--no-ansi                  Disable ANSI output
-n, --no-interaction           Do not ask any interactive question
-d, --active-dir=ACTIVE-DIR    Use the given directory as active directory [default: "/Users/travis.carden/Projects/autoupdates/composer-stager"]
-s, --staging-dir=STAGING-DIR  Use the given directory as staging directory [default: …
```
=> Implement "clean" command

composer.json, config/services.yml, src/Domain/Beginner.php, src/Domain/Committer.php, src/Infrastructure/Process/FileCopier/FileCopierFactory.php, src/Infrastructure/Process/FileCopier/FileCopierFactoryInterface.php, src/Infrastructure/Process/FileCopier/FileCopierInterface.php, src/Infrastructure/Process/FileCopier/RsyncFileCopier.php, src/Infrastructure/Process/FileCopier/RsyncFileCopierInterface.php, src/Infrastructure/Process/FileCopier/SymfonyFileCopier.php, src/Infrastructure/Process/FileCopier/SymfonyFileCopierInterface.php, src/Infrastructure/Process/Runner/RsyncRunner.php, tests/Functional/EndToEndTest.php, tests/Functional/FrontScriptTest.php, tests/Functional/SymfonyFileCopierTest.php, tests/Functional/TestCase.php, tests/Unit/Domain/BeginnerTest.php, tests/Unit/Domain/CommitterTest.php, tests/Unit/Infrastructure/Process/FileCopier/FileCopierFactoryTest.php, tests/Unit/Infrastructure/Process/FileCopier/RsyncFileCopierTest.php, tests/Unit/Infrastructure/Process/FileCopier/SymfonyFileCopierTest.php
This adds a Symfony Filesystem-based file copier that's automatically used on hosts (like Windows) that don't have `rsync` available. It also adds full, end-to-end functional testing of the entire project. Functional tests are currently restricted to the happy path. We can decide later which edge error/edge conditions are important enough to test.
=> Add Symfony-based rsync file copier alternative and end-to-end functional test coverage

src/Domain/Beginner.php, src/Domain/BeginnerInterface.php, src/Domain/Cleaner.php, src/Domain/CleanerInterface.php, src/Domain/Committer.php, src/Domain/CommitterInterface.php, src/Domain/Stager.php, src/Domain/StagerInterface.php, src/Infrastructure/Filesystem/Filesystem.php, src/Infrastructure/Filesystem/FilesystemInterface.php, src/Infrastructure/Process/FileCopier/FileCopierInterface.php, src/Infrastructure/Process/FileCopier/RsyncFileCopier.php, src/Infrastructure/Process/FileCopier/SymfonyFileCopier.php, src/Infrastructure/Process/Runner/AbstractRunner.php, src/Infrastructure/Process/Runner/ComposerRunnerInterface.php, src/Infrastructure/Process/Runner/RsyncRunner.php, src/Infrastructure/Process/Runner/RsyncRunnerInterface.php, tests/Unit/Domain/BeginnerTest.php, tests/Unit/Domain/CleanerTest.php, tests/Unit/Domain/CommitterTest.php, tests/Unit/Domain/StagerTest.php, tests/Unit/Infrastructure/Filesystem/FilesystemTest.php, tests/Unit/Infrastructure/Process/FileCopier/SymfonyFileCopierTest.php, tests/Unit/Infrastructure/Process/Runner/AbstractRunnerTest.php
A Drupal code base can be quite large, so the default process timeout of 60 (or is it 30?) seconds is relatively easy to run into. We should allow the process runners to have a larger timeout if needed (say, 5 minutes), as determined by the calling code.
=> Allow process runners to accept an arbitrary timeout

composer.json, composer.lock
The Composer 2.2 release includes a new feature for [more secure plugin execution](https://blog.packagist.com/composer-2-2/#:~:text=more%20secure%20plugin%20execution), which requires allowed plugins to be explicitly declared in your `composer.json`:
```
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.
```
This PR adds the new config.
=> Add Composer allow-plugins config

src/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinks.php, tests/PHPUnit/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinksFunctionalTest.php, tests/PHPUnit/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinksUnitTest.php
This adds detail to the error message from the `CodeBaseContainsNoSymlinks` precondition:
```diff
- The codebase contains symlinks.
+ The active directory at "/var/www/example" contains symlinks, which is not supported.
```
=> Add detail to CodeBaseContainsNoSymlinks error message

src/Domain/Service/Precondition/CodebaseContainsNoSymlinksInterface.php, src/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinks.php, tests/PHPUnit/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinksFunctionalTest.php, tests/PHPUnit/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinksUnitTest.php
…and expand existing test coverage.
=> Explicitly contract that CodebaseContainsNoSymlinksInterface will ignore non-existent directories

src/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinks.php, tests/PHPUnit/Infrastructure/Service/Precondition/CodeBaseContainsNoSymlinksFunctionalTest.php
This improves the usefulness of the "codebase contains symlinks" error message by including the pathname of the first one found. The difference looks like this:
```diff
- The active directory at "var/www" contains symlinks, which is not supported.
+ The active directory at "var/www" contains symlinks, which is not supported. The first one is "var/www/symlink.txt".
```
=> Enhance the "codebase contains symlinks" error message by showing the first one found

src/Infrastructure/Service/Finder/ExecutableFinder.php, tests/PHPUnit/Infrastructure/Service/Finder/ExecutableFinderUnitTest.php
`Infrastructure\Service\Finder\ExecutableFinder` caches not only an executable path when it's found but the exception thrown when it's not, resulting in an incorrect backtrace if it called more than once via different code paths in the same process.
This caching was premature optimization to begin with. Just remove it.
=> Infrastructure\Service\Finder\ExecutableFinder incorrectly caches exception backtraces

src/Infrastructure/Service/Precondition/AbstractFileIteratingPrecondition.php, src/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExist.php, src/Infrastructure/Service/Precondition/NoHardLinksExist.php, src/Infrastructure/Service/Precondition/NoLinksExistOnWindows.php, src/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebase.php, tests/EndToEnd/PhpFileSyncerEndToEndFunctionalTest.php, tests/Infrastructure/Service/Precondition/AbstractFileIteratingPreconditionUnitTest.php, tests/Infrastructure/Service/Precondition/FileIteratingPreconditionUnitTestCase.php, tests/Infrastructure/Service/Precondition/LinkPreconditionsIsolationFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExistUnitTest.php, tests/Infrastructure/Service/Precondition/NoHardLinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoHardLinksExistUnitTest.php, tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsUnitTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseUnitTest.php
Emphasis on _Link_ iterating to _File_ iterating. This refactoring improves the semantics of link-related preconditions, effectively answering @wimleers feedback in https://github.com/php-tuf/composer-stager/pull/100, I believe, and preparing the way for future enhancements like https://github.com/php-tuf/composer-stager/issues/67, which will also need to iterate over all files, not just links.
=> Generalize AbstractLinkIteratingPrecondition as AbstractFileIteratingPrecondition

src/Infrastructure/Service/FileSyncer/RsyncFileSyncer.php, tests/Infrastructure/Service/FileSyncer/FileSyncerFunctionalTestCase.php, tests/Infrastructure/Service/FileSyncer/PhpFileSyncerFunctionalTest.php, tests/Infrastructure/Service/FileSyncer/RsyncFileSyncerFunctionalTest.php
The `Infrastructure\Service\FileSyncer\RsyncFileSyncer::sync()` method currently ignores the `$timeout` argument.
=> Make Infrastructure\Service\FileSyncer\RsyncFileSyncer::sync() respect $timeout

src/Infrastructure/Service/Filesystem/Filesystem.php, tests/Infrastructure/Service/Filesystem/FilesystemFunctionalTest.php
As discovered at https://www.drupal.org/project/automatic_updates/issues/3319507#comment-14972129, `Infrastructure\Service\Filesystem\Filesystem::readLink()` resolves symlinks relative to the CWD of the running PHP process, not the directory the link is in, like it should.
=> Filesystem::readLink() resolves links relative to the PHP process' CWD instead of the link directory

src/Domain/Core/Beginner/Beginner.php, src/Domain/Core/Cleaner/Cleaner.php, src/Domain/Core/Committer/Committer.php, src/Domain/Core/Stager/Stager.php, src/Infrastructure/Factory/Process/ProcessFactory.php, src/Infrastructure/Service/FileSyncer/RsyncFileSyncer.php, src/Infrastructure/Service/Filesystem/Filesystem.php, src/Infrastructure/Service/Finder/RecursiveFileFinder.php, src/Infrastructure/Service/ProcessRunner/AbstractRunner.php
When wrapping exceptions in many instances, Composer Stager reuses the exception code of the wrapped exception. This is unnecessary, since the same value is already accessible via `::getPrevious()->getCode()`, and undesirable, since it introduces uncertainty or even indeterminism, as domain exception codes depend on third party code. Use the default values now in lieu of https://github.com/php-tuf/composer-stager/issues/71.
=> Normalize exception codes at default values

src/Domain/Core/Stager/Stager.php, src/Domain/Value/Path/PathInterface.php, src/Infrastructure/Service/FileSyncer/PhpFileSyncer.php, src/Infrastructure/Service/FileSyncer/RsyncFileSyncer.php, src/Infrastructure/Service/Filesystem/Filesystem.php, src/Infrastructure/Service/Finder/RecursiveFileFinder.php, src/Infrastructure/Service/Precondition/AbstractFileIteratingPrecondition.php, src/Infrastructure/Service/Precondition/ActiveAndStagingDirsAreDifferent.php, src/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebase.php, src/Infrastructure/Value/Path/AbstractPath.php, tests/EndToEnd/EndToEndFunctionalTestCase.php, tests/Infrastructure/Service/FileSyncer/FileSyncerFunctionalTestCase.php, tests/Infrastructure/Service/FileSyncer/PhpFileSyncerUnitTest.php, tests/Infrastructure/Service/FileSyncer/RsyncFileSyncerUnitTest.php, tests/Infrastructure/Service/Filesystem/FilesystemFunctionalTest.php, tests/Infrastructure/Service/Filesystem/FilesystemUnitTest.php, tests/Infrastructure/Service/Finder/RecursiveFileFinderFunctionalTest.php, tests/Infrastructure/Service/Precondition/ActiveAndStagingDirsAreDifferentUnitTest.php, tests/Infrastructure/Service/Precondition/LinkPreconditionsIsolationFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoHardLinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointToADirectoryFunctionalTest.php, tests/Infrastructure/Service/Precondition/PreconditionTestCase.php, tests/Infrastructure/Value/Path/TestPath.php, tests/Infrastructure/Value/Path/UnixLikePathUnitTest.php, tests/Infrastructure/Value/Path/WindowsPathUnitTest.php, tests/TestCase.php
`Domain\Value\Path\PathInterface::resolve()` and `::resolveRelativeTo()` sound like mutators, but they are, in fact, pure functions. Rename them to make this clearer:
```diff
-::resolve()
+::resolved()
-::resolveRelativeTo()
+::resolvedRelativeTo()
```
=> Rename PathInterface::resolve() and ::resolveRelativeTo()

src/Domain/Core/Beginner.php, src/Domain/Core/BeginnerInterface.php, src/Domain/Core/Cleaner.php, src/Domain/Core/CleanerInterface.php, src/Domain/Core/Committer.php, src/Domain/Core/Committer/CommitterInterface.php, src/Domain/Core/CommitterInterface.php, src/Domain/Core/Stager.php, src/Domain/Core/StagerInterface.php, tests/Domain/Core/BeginnerUnitTest.php, tests/Domain/Core/CleanerUnitTest.php, tests/Domain/Core/CommitterUnitTest.php, tests/Domain/Core/StagerUnitTest.php, tests/EndToEnd/EndToEndFunctionalTestCase.php, tests/EndToEnd/PhpFileSyncerEndToEndFunctionalTest.php
There's no need for each core domain class to have it's own namespace, since it will only ever have one class in it. This moves the four of them up a level together into `Domain\Core`.
```
src/Domain/Core/{Beginner => }/Beginner.php
src/Domain/Core/{Beginner => }/BeginnerInterface.php
src/Domain/Core/{Cleaner => }/Cleaner.php
src/Domain/Core/{Cleaner => }/CleanerInterface.php
src/Domain/Core/{Committer => }/Committer.php
src/Domain/Core/{Committer => }/CommitterInterface.php
src/Domain/Core/{Stager => }/Stager.php
src/Domain/Core/{Stager => }/StagerInterface.php
```
=> Move core domain classes up a namespace level

phpstan.neon.dist, src/Infrastructure/Service/FileSyncer/PhpFileSyncer.php, src/Infrastructure/Service/Finder/FileFinder.php, src/Infrastructure/Service/Finder/FileFinderInterface.php, src/Infrastructure/Service/Precondition/AbstractFileIteratingPrecondition.php, src/Infrastructure/Service/Precondition/NoLinksExistOnWindows.php, src/Infrastructure/Service/Precondition/NoSymlinksPointToADirectory.php, tests/EndToEnd/PhpFileSyncerEndToEndFunctionalTest.php, tests/Infrastructure/Service/FileSyncer/PhpFileSyncerFunctionalTest.php, tests/Infrastructure/Service/FileSyncer/PhpFileSyncerUnitTest.php, tests/Infrastructure/Service/Finder/FileFinderFunctionalTest.php, tests/Infrastructure/Service/Precondition/AbstractFileIteratingPreconditionUnitTest.php, tests/Infrastructure/Service/Precondition/FileIteratingPreconditionUnitTestCase.php, tests/Infrastructure/Service/Precondition/NoAbsoluteSymlinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoHardLinksExistFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoHardLinksExistUnitTest.php, tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoLinksExistOnWindowsUnitTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointOutsideTheCodebaseUnitTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointToADirectoryFunctionalTest.php, tests/Infrastructure/Service/Precondition/NoSymlinksPointToADirectoryUnitTest.php
`RecursiveFileFinderInterface` is needlessly specific and could cause confusion when other implementations or similar interfaces are added... which is likely.
=> Rename RecursiveFileFinderInterface to FileFinderInterface

phpstan.neon.dist, src/Internal/Filesystem/Service/Filesystem.php, src/Internal/Precondition/Service/ComposerIsAvailable.php, tests/Filesystem/Service/FilesystemUnitTest.php
A little debugging data is helpful if `Filesystem::copy()` fails. This passes along whatever detail Symfony Filesystem provides.
=> Include "previous" exception details in thrown exception in Filesystem::copy()

src/API/Core/BeginnerInterface.php, src/API/Core/CleanerInterface.php, src/API/Core/CommitterInterface.php, src/API/Core/StagerInterface.php, src/API/FileSyncer/Service/FileSyncerInterface.php, src/API/Filesystem/Service/FilesystemInterface.php, src/API/Process/Service/ComposerProcessRunnerInterface.php, src/API/Process/Service/ProcessInterface.php, src/API/Process/Service/RsyncProcessRunnerInterface.php, src/Internal/Core/Beginner.php, src/Internal/Core/Cleaner.php, src/Internal/Core/Committer.php, src/Internal/Core/Stager.php, src/Internal/FileSyncer/Service/PhpFileSyncer.php, src/Internal/FileSyncer/Service/RsyncFileSyncer.php, src/Internal/Filesystem/Service/Filesystem.php, src/Internal/Process/Service/AbstractProcessRunner.php, src/Internal/Process/Service/Process.php, tests/Core/BeginnerUnitTest.php, tests/Core/CleanerUnitTest.php, tests/Core/CommitterUnitTest.php, tests/Core/StagerUnitTest.php, tests/FileSyncer/Service/FileSyncerFunctionalTestCase.php, tests/Filesystem/Service/FilesystemUnitTest.php, tests/Process/Service/AbstractProcessRunnerUnitTest.php
`$timeout` arguments used to take `null` to disable timeout. This changes them to be-non-nullable and take zero (0) instead to impose no limit, in line with [`set_time_limit()`](https://www.php.net/manual/en/function.set-time-limit.php).
=> Make `$timeout` arguments non-nullable

src/Internal/Environment/Service/Environment.php, src/Internal/Environment/Service/EnvironmentInterface.php, src/Internal/FileSyncer/Service/PhpFileSyncer.php, src/Internal/FileSyncer/Service/RsyncFileSyncer.php, src/Internal/Filesystem/Service/Filesystem.php, tests/Environment/Service/EnvironmentFunctionalTest.php, tests/FileSyncer/Service/FileSyncerTestCase.php, tests/FileSyncer/Service/PhpFileSyncerUnitTest.php, tests/FileSyncer/Service/RsyncFileSyncerUnitTest.php, tests/Filesystem/Service/FilesystemUnitTest.php
Fixes https://github.com/php-tuf/composer-stager/issues/253
Some shared hosting disables the PHP `set_time_limit()` function, so calls to it cause fatal errors. This makes sure the function exists before calling it and ignores the timeout if not.
=> Degrade gracefully when `set_time_limit()` is disabled

tests/Compatability/CompatabilityFunctionalTest.php
See new [Library compatibility policy](https://github.com/php-tuf/composer-stager/wiki/Library-compatibility-policy). tl;dr:
| Major version | Minor version | Point release | Example |
|---|---|---|---|
| Current | Oldest supported | Oldest available | `10.0.0` |
| Current | Oldest supported | Newest available | `10.0.10` |
| Current | Current | Oldest available | `10.1.0` |
| Current | Current | Newest available | `10.1.2` |
| Current | Next | Dev | `11.x-dev` |
=> Document and add tests for expanded Drupal core supported versions spread

.github/workflows/main.yml, .idea/php.xml, composer.json, composer.lock, infection.json.dist, src/Internal/Helper/PathHelper.php, tests/Core/BeginnerUnitTest.php, tests/Core/CleanerUnitTest.php, tests/Core/CommitterUnitTest.php, tests/Core/StagerUnitTest.php, tests/FileSyncer/Service/PhpFileSyncerUnitTest.php, tests/FileSyncer/Service/RsyncFileSyncerUnitTest.php, tests/Filesystem/Service/FilesystemUnitTest.php, tests/Precondition/Service/ComposerIsAvailableFunctionalTest.php, tests/Precondition/Service/ComposerIsAvailableUnitTest.php, tests/Precondition/Service/PreconditionTestCase.php, tests/Process/Service/ProcessUnitTest.php, tests/TestUtils/AssertTrait.php
This adds mutation testing with [Infection](https://infection.github.io/), including a new CI job that runs it. (It _should_ [automatically comment on pull requests](https://infection.github.io/guide/command-line-options.html#logger-github); we'll see.)
Also included are some changes to bring the mutation score up a little (from 82% to 89%) for illustration.
**Note**: This brings in some new transitive dev dependencies, which can be discussed separately:
| Dev Changes                              | From | To     | Compare |
|------------------------------------------|------|--------|---------|
| colinodell/json5                         | NEW  | v2.3.0 |         |
| fidry/cpu-core-counter                   | NEW  | 0.5.1  |         |
| infection/abstract-testframework-adapter | NEW  | …
=> Add mutation testing

phpstan.neon.dist, src/Internal/Precondition/Service/HostSupportsRunningProcesses.php, src/Internal/Precondition/Service/NoAbsoluteSymlinksExist.php, src/Internal/Precondition/Service/NoHardLinksExist.php, src/Internal/Precondition/Service/NoLinksExistOnWindows.php, src/Internal/Precondition/Service/NoSymlinksPointOutsideTheCodebase.php, src/Internal/Precondition/Service/NoSymlinksPointToADirectory.php, tools/PHPStan/Rules/Calls/ValidTranslatableStringsRule.php
This new rule requires that all `$message` arguments to `Internal\Translation\Factory\TranslatableAwareTrait::t()` are literal strings. It also merges concatenated messages already in the codebase, because, while researching this issue, I discovered that those are not supported by Drupal's [Translation Template Extractor](https://www.drupal.org/project/potx). (Double win!)
=> Fix some untranslatable UI strings and add a PHPStan rule to prevent introducing any more

src/API/Filesystem/Service/FilesystemInterface.php, src/Internal/Filesystem/Service/Filesystem.php, tests/Filesystem/Service/FilesystemFunctionalTest.php
`Filesystem::filePerms()` currently tries to convert the result of `fileperms()` into a three digit mode value, but this turns out to be unreliable given octal permissions--and it diverges from the behavior of its corresponding PHP core function, `fileperms()`, anyway. Just stop doing any conversion at all.
=> Stop trying to convert `fileperms()` result in `Internal\Filesystem\Service\Filesystem::filePerms()`

phpstan.neon.dist, src/API/Filesystem/Service/FilesystemInterface.php, src/Internal/FileSyncer/Service/PhpFileSyncer.php, src/Internal/FileSyncer/Service/RsyncFileSyncer.php, src/Internal/Filesystem/Service/Filesystem.php, src/Internal/Precondition/Service/AbstractFileIteratingPrecondition.php, src/Internal/Precondition/Service/ActiveDirExists.php, src/Internal/Precondition/Service/StagingDirDoesNotExist.php, src/Internal/Precondition/Service/StagingDirExists.php, tests/FileSyncer/Service/PhpFileSyncerUnitTest.php, tests/FileSyncer/Service/RsyncFileSyncerUnitTest.php, tests/Filesystem/Service/FilesystemFunctionalTest.php, tests/Precondition/Service/AbstractFileIteratingPreconditionUnitTest.php, tests/Precondition/Service/ActiveDirExistsUnitTest.php, tests/Precondition/Service/FileIteratingPreconditionUnitTestCase.php, tests/Precondition/Service/NoLinksExistOnWindowsUnitTest.php, tests/Precondition/Service/NoSymlinksPointOutsideTheCodebaseUnitTest.php, tests/Precondition/Service/NoSymlinksPointToADirectoryUnitTest.php, tests/Precondition/Service/StagingDirDoesNotExistUnitTest.php, tests/Precondition/Service/StagingDirExistsUnitTest.php
...for closer correspondence to [PHP's built-in filesystem function names](https://www.php.net/manual/en/ref.filesystem.php).
=> Rename `FilesystemInterface::exists()` to `::fileExists()`

src/API/Filesystem/Service/FilesystemInterface.php, src/Internal/FileSyncer/Service/PhpFileSyncer.php, src/Internal/Filesystem/Service/Filesystem.php, tests/FileSyncer/Service/FileSyncerFunctionalTestCase.php, tests/FileSyncer/Service/PhpFileSyncerUnitTest.php, tests/Filesystem/Service/FilesystemFunctionalTest.php, tests/TestUtils/VfsHelper.php
It's only used in one place, and it doesn't fit nicely into the design intent of "corresponding as much as possible to PHP's built-in filesystem functions".
=> Remove `API\Filesystem\Service\FilesystemInterface::isDirEmpty()`

src/API/Filesystem/Service/FilesystemInterface.php, src/Internal/Core/Cleaner.php, src/Internal/FileSyncer/Service/PhpFileSyncer.php, src/Internal/Filesystem/Service/Filesystem.php, tests/Core/CleanerUnitTest.php, tests/Filesystem/Service/FilesystemUnitTest.php
...for closer correspondence to [PHP's built-in filesystem function names](https://www.php.net/manual/en/ref.filesystem.php).
=> Rename `Internal\Filesystem\Service\Filesystem::remote()` to `::rm()`

src/API/Process/Factory/ProcessFactoryInterface.php, src/API/Process/Service/ComposerProcessRunnerInterface.php, src/API/Process/Service/RsyncProcessRunnerInterface.php, src/Internal/Core/Stager.php, src/Internal/FileSyncer/Service/RsyncFileSyncer.php, src/Internal/Process/Factory/ProcessFactory.php, src/Internal/Process/Factory/SymfonyProcessFactory.php, src/Internal/Process/Factory/SymfonyProcessFactoryInterface.php, src/Internal/Process/Service/AbstractProcessRunner.php, src/Internal/Process/Service/Process.php, tests/Core/StagerUnitTest.php, tests/FileSyncer/Service/RsyncFileSyncerUnitTest.php, tests/Process/Factory/ProcessFactoryUnitTest.php, tests/Process/Factory/SymfonyProcessFactoryUnitTest.php, tests/Process/Service/AbstractProcessRunnerUnitTest.php, tests/Process/Service/ProcessUnitTest.php
This enables the direct setting of environment variables (`$env`) via the constructor and invocation methods of the `Process` creation chain (as opposed to depending solely on the `::setEnv()` method on the `Process` class itself):
- `AbstractProcessRunner::run()`
- `ProcessFactory::create()`.
- `Process::__construct()`
- `SymfonyProcessFactory::create()`
=> Add `$env` argument to `Process` creation chain

src/API/Process/Service/ComposerProcessRunnerInterface.php, src/API/Process/Service/RsyncProcessRunnerInterface.php, src/Internal/Core/Stager.php, src/Internal/FileSyncer/Service/RsyncFileSyncer.php, src/Internal/Process/Factory/SymfonyProcessFactory.php, src/Internal/Process/Factory/SymfonyProcessFactoryInterface.php, src/Internal/Process/Service/AbstractProcessRunner.php, src/Internal/Process/Service/Process.php, tests/Core/StagerUnitTest.php, tests/FileSyncer/Service/RsyncFileSyncerUnitTest.php, tests/Process/Factory/SymfonyProcessFactoryUnitTest.php, tests/Process/Service/AbstractProcessRunnerUnitTest.php, tests/Process/Service/ProcessUnitTest.php
This enables the direct setting of the current working directory (`$env`) via the constructor and invocation methods of the `Process` creation chain (which cannot currently be accomplished by any other means):
- `AbstractProcessRunner::run()`
- `ProcessFactory::create()`.
- `Process::__construct()`
- `SymfonyProcessFactory::create()`
=> Add `$cwd` argument to `Process` creation chain

src/API/Filesystem/Service/FilesystemInterface.php, src/Internal/Filesystem/Service/Filesystem.php, tests/Filesystem/Service/FilesystemFunctionalTest.php
Actually, `::isFile()` already does, but its docblock says it doesn't (so fix that).
=> Make `API\Filesystem\Service\FilesystemInterface::isDir()` and `::isFile()` resolve links like their PHP built-in counterparts

phpstan.neon.dist, src/Internal/Precondition/Service/ActiveDirExists.php, src/Internal/Precondition/Service/StagingDirExists.php, tests/Precondition/Service/ActiveDirExistsUnitTest.php, tests/Precondition/Service/StagingDirExistsUnitTest.php
The `ActiveDirExists` and `StagingDirExists` preconditions currently assert that the paths exist but not that they're actually directories (as opposed to regular files, for example).
=> Make sure active and staging directories are actually directories

src/API/Process/Service/ProcessInterface.php, src/Internal/Process/Service/Process.php, tests/Precondition/Service/ComposerIsAvailableUnitTest.php, tests/Precondition/Service/RsyncIsAvailableUnitTest.php, tests/Process/Service/AbstractProcessRunnerUnitTest.php, tests/Process/Service/ProcessUnitTest.php
Making `API\Process\Service\ProcessInterface` methods fluid and returning `self`, following the lead of `symfony/process` seemed like a good idea at the time, but in retrospect probably provides negligible benefit, and it complicates unit tests, not to mention being the only part of the codebase that uses the pattern. This changes the methods to return `void`.
=> Stop returning `self` from `API\Process\Service\ProcessInterface` methods

phpstan.neon.dist, src/Internal/Precondition/Service/ComposerIsAvailable.php, tests/Precondition/Service/ComposerIsAvailableFunctionalTest.php, tests/Precondition/Service/ComposerIsAvailableUnitTest.php
Fixes: https://github.com/php-tuf/composer-stager/issues/348
This makes it possible to modify Composer command behavior everywhere (e.g., by adding environment variables) by just overriding `ComposerProcessRunner` once.
=> Make `ComposerIsAvailable` use `ComposerProcessRunner` instead of `ProcessFactory`

phpcs.xml.dist, phpstan.neon.dist, phpunit.xml.dist, rector.php, src/Internal/Process/Factory/SymfonyProcessFactory.php, src/Internal/Process/Factory/SymfonyProcessFactoryInterface.php, src/Internal/Process/Service/Process.php, src/Internal/SymfonyProcess/Value/AbstractPipes.php, src/Internal/SymfonyProcess/Value/FixedSymfonyProcess.php, src/Internal/SymfonyProcess/Value/PipesInterface.php, src/Internal/SymfonyProcess/Value/UnixPipes.php, src/Internal/SymfonyProcess/Value/WindowsPipes.php, tests/Process/Factory/SymfonyProcessFactoryUnitTest.php, tests/Process/Service/ProcessUnitTest.php, tests/TestUtils/builtin_function_mocks.inc
Processes recently stopped capturing error output and tests started failing due to an upstream regression in Symfony Process reported in https://github.com/symfony/symfony/pull/57317. We can't pin to the last working version, because we can't constrain our users; and the internals upstream make it impossible to selectively extend and override. So this PR temporarily works around it by just forking `\Symfony\Component\Process\Process` and the few internal classes it depends on. Happily, it requires very little code modification, and it has no impact on the public API.
=> Fix process error output-capturing broken by upstream regression

phpstan.neon.dist, src/Internal/Precondition/Service/RsyncIsAvailable.php, tests/Precondition/Service/FileIteratingPreconditionUnitTestCase.php, tests/Precondition/Service/PreconditionUnitTestCase.php, tests/Precondition/Service/RsyncIsAvailableFunctionalTest.php, tests/Precondition/Service/RsyncIsAvailableUnitTest.php
`Internal\Precondition\Service\RsyncIsAvailable::isValidExecutable()` was written with the assumption that a valid `rsync` executable will always output a version beginning with the string `rsync`; but this turns out not to be the case, as illustrated here:
```
$ rsync --version
openrsync: protocol version 29
rsync version 2.6.9 compatible
```
This PR makes the test more robust by looking for `rsync version` at the beginning of _any_ line of output (ignoring spacing)
=> Make `Internal\Precondition\Service\RsyncIsAvailable` more robust

composer.json, composer.lock
`symfony/process` has announced a high severity vulnerability: [CVE-2024-51736 - Symfony vulnerable to command execution hijack on Windows with Process class](https://github.com/advisories/GHSA-qq5c-677p-737q). This could lead to serious compromises for users of Composer Stager. In order to prevent that, this adds Composer conflicts with vulnerable versions.
=> Declare conflicts with vulnerable versions of symfony/process
